version: '3.8'
services:
  postgres.dev:
    image: postgres:14
    logging:
      driver: none
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: iamroot
      POSTGRES_USER: lula_root
      POSTGRES_DB: root
    volumes:
      - app.postgres:/var/lib/postgresql/data

volumes:
  app.postgres: